
name: Build and deploy Node.js app to Azure Web App - smw-test2-app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'smw-test2-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_35016c3a69194205a26740251d80c970 }}
        package: .
